# Generated by Django 4.2.2 on 2023-07-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'residencial'), ('comercial', 'comercial')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
