# Generated by Django 3.2.4 on 2021-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_numerotelefonico_costo_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='comentario',
            field=models.CharField(default='sin comentarios', max_length=30),
            preserve_default=False,
        ),
    ]
